run_modules:
  - dragen

title: "QC Metrics Summary"
intro_text: ""

report_header_info:
  - Contact E-mail: "dummy@tyrolpath.at"
  - Application Type: "Whole Exome Sequencing"
  - Sequencing Platform: "Illumina NovaSeq6000"
  - Sequencing Setup: "2x150"

custom_plot_config:
  # Add a coloured band in the background to show what is a good result
  # Yes I know this doesn't make sense for this plot, it's just an example ;)
  dragen_coverage_dist:
    xPlotBands:
      - from: 0
        to: 250
        color: "#CB433520"
      - from: 250
        to: 350
        color: "#F4D03F20"
      - from: 350
        to: 3000
        color: "#27AE6020"

table_cond_formatting_rules:
  mqc-generalstats-dragen_coverage-Average_alignment_coverage_over_target_region:
    warn:
      - lt: 300
    fail:
      - lt: 250
  mqc-generalstats-dragen_mapping-Insert_length_median:
    warn:
      - lt: 170
    fail:
      - lt: 140
    warn:
      - gt: 250
    fail:
      - gt: 270
  mqc-generalstats-dragen_coverage-PCT_of_target_region_with_coverage_0x_1x:
    warn:
      - gt: 2.1
    fail:
      - gt: 2.4
  mqc-generalstats-dragen_coverage-PCT_of_target_region_with_coverage_100x_inf:
    warn:
      - lt: 92
    fail:
      - lt: 90
  mqc-generalstats-dragen_mapping-Number_of_duplicate_marked_reads_pct:
    warn:
      - gt: 40
    fail:
      - gt: 50
  mqc-generalstats-dragen_mapping-Q30_bases_pct:
    warn:
      - lt: 88
    fail:
      - lt: 85
  mqc-generalstats-dragen_coverage-Uniformity_of_coverage_PCT_0_2_mean_over_target_region:
    warn:
      - lt: 94
    fail:
      - lt: 93