name: Lint Code Base
on: [push, pull_request]

jobs:
  Prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Install Prettier
        run: npm install -g prettier

      - name: Run Prettier --check
        run: prettier --check ${GITHUB_WORKSPACE}

  PythonBlack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check code lints with Black
        uses: jpetrucciani/black-check@master

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check imports with isort
        uses: jamescurtin/isort-action@master

  CodeChecks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install rich

      - name: Run manual code style checks
        run: python ${GITHUB_WORKSPACE}/.github/workflows/code_checks.py

  MergeMarkers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Grep for >>>>>>>
        run: |
          if [[ $(grep -ER "$>>>>>>> " . | wc -l) > 0 ]];then
            echo "Opening merge marker found\!"
            grep -ER "$>>>>>>> " .
            exit 1
          else
            echo "No opening merge markers found"
            exit 0
          fi

      - name: Grep for <<<<<<<
        run: |
          if [[ $(grep -ER "$<<<<<<< " . | wc -l) > 0 ]];then
            echo "Closing merge marker found\!"
            grep -ER "$>>>>>>> " .
            exit 1
          else
            echo "No closing merge markers found"
            exit 0
          fi
